name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: ./deploy.yml
